# Generated by Django 4.2.6 on 2023-11-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_producttype_size_productitem_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'default_related_name': 'product_items', 'verbose_name': 'Product item', 'verbose_name_plural': 'Product items'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.producttype'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='color',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='product.color'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='product.size'),
        ),
        migrations.RemoveField(
            model_name='color',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.RemoveField(
            model_name='size',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.brand'),
        ),
        migrations.AddField(
            model_name='color',
            name='product_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='product.producttype'),
        ),
        migrations.AddField(
            model_name='size',
            name='product_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='product.producttype'),
        ),
    ]
