# Generated by Django 4.2.6 on 2023-11-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_name_az_category_name_en_category_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='product.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.producttype'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.color'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='product.producttype'),
        ),
    ]
