# Generated by Django 4.2.6 on 2023-11-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='endprice',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
