# Generated by Django 4.2.6 on 2023-11-18 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_appealing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
