# Generated by Django 4.2.6 on 2023-11-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutpoint_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Haqqımızda', 'verbose_name_plural': 'Haqqımızda'},
        ),
    ]
